
[kubernetes]
disabled = false
[[kubernetes.contexts]]
context_pattern = "arn.*/(?P<var_cluster>[\\w-]+)"
context_alias = "aws-$var_cluster"
[terraform]
disabled = true
[gcloud]
disabled = true
[git_branch]
truncation_length = 30
[shell]
fish_indicator = 'ó°ˆº '
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false
